/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.vista;

import edu.cecar.controlador.ControladorCorreo;
import edu.cecar.controlador.ControladorMensaje;
import edu.cecar.controlador.ControladorSms;
import edu.cecar.modelo.Credencial;
import edu.cecar.modelo.Mensaje;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Part;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yanvier
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    private List<Credencial> credenciales = new ArrayList();

    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        correoTf = new javax.swing.JTextField();
        passTf = new javax.swing.JPasswordField();
        tipoCuentaCb = new javax.swing.JComboBox<>();
        agregarBtn = new javax.swing.JButton();
        nuevoBtn = new javax.swing.JButton();
        inboxBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajesTb = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        celularTf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        alertaChb = new javax.swing.JCheckBox();
        activarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filtroTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Correos");

        jLabel1.setText("Correo Electronico");

        jLabel2.setText("Contraseña");

        tipoCuentaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo de cuenta", "Gmail", "Hotmail-Outlook" }));

        agregarBtn.setText("Añadir cuenta");
        agregarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarBtnMouseClicked(evt);
            }
        });
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        nuevoBtn.setText("Nuevo");
        nuevoBtn.setEnabled(false);
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        inboxBtn.setText("Actualizar");
        inboxBtn.setEnabled(false);
        inboxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxBtnActionPerformed(evt);
            }
        });

        mensajesTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asunto", "Enviado Por:", "Cuenta", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mensajesTb);

        celularTf.setEditable(false);
        celularTf.setText("+573166845456");
        celularTf.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        alertaChb.setText("Enviar Alertas");
        alertaChb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertaChbActionPerformed(evt);
            }
        });

        activarBtn.setText("Activar Alertas");
        activarBtn.setEnabled(false);

        jLabel3.setText("N° de Celular:");

        jLabel4.setText("Hay que probar con ese numero de telefono ya que el servicio es muy limitado");

        jLabel5.setText("Fitro Alerta:");

        filtroTf.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passTf, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(tipoCuentaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agregarBtn)
                                .addGap(32, 32, 32)))
                        .addGap(58, 58, 58)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filtroTf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(activarBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap(34, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(celularTf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alertaChb)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nuevoBtn)
                                .addGap(310, 310, 310)
                                .addComponent(inboxBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(celularTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alertaChb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(filtroTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activarBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(correoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoCuentaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(passTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarBtn)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoBtn)
                    .addComponent(inboxBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        // TODO add your handling code here:

        Credencial credencial = new Credencial();
        String correo = "";
        String pass = "";
        String tipoCuenta = "";

        correo = correoTf.getText();
        pass = passTf.getText();
        tipoCuenta = tipoCuentaCb.getSelectedItem().toString();

        if ("".equals(correo) || "".equals(pass) || "".equals(tipoCuenta) || tipoCuentaCb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Hay campos vacios");
        } else {
            inboxBtn.setEnabled(true);

            credencial.setEmail(correo);
            credencial.setPassword(pass);
            credencial.setTipoCuenta(tipoCuenta);
            credenciales.add(credencial);

        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void agregarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarBtnMouseClicked
        // TODO add your handling code here:
        //Credencial credencial =new Credencial();
        correoTf.setText("");
        passTf.setText("");
        tipoCuentaCb.setSelectedIndex(0);
    }//GEN-LAST:event_agregarBtnMouseClicked

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        // TODO add your handling code here:
        ControladorCorreo cc = new ControladorCorreo();
        EnviarMensaje em = new EnviarMensaje();
        JComboBox combo = em.cuentasCb;

        for (Credencial credencial : credenciales) {
            String correo = credencial.getEmail();
            combo.addItem(correo);
        }
        em.enviarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String cuenta = combo.getSelectedItem().toString();
                for (Credencial credencial : credenciales) {
                    String correo = credencial.getEmail();
                    String pass = credencial.getPassword();
                    String tipoCuenta = credencial.getTipoCuenta();
                    if (cuenta.equals(correo)) {
                        String asunto = em.asuntoTf.getText();
                        String mensaje = em.mensajeTa.getText();
                        String destino = em.paraTf.getText();
                        boolean response = cc.enviarCorreo(correo, pass, tipoCuenta, destino, asunto, mensaje);

                        if (response = true) {
                            JOptionPane.showMessageDialog(null, "MENSAJE ENVIADO CON EXITO");

                            //System.exit(0);
                        }
                        if (response = false) {
                            JOptionPane.showMessageDialog(null, "HA OCURRIDO UN ERROR");
                        }

                    }
                }
            }
        });

        em.setVisible(true);

    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void inboxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxBtnActionPerformed
        // TODO add your handling code here:
        nuevoBtn.setEnabled(true);
        ControladorCorreo cc = new ControladorCorreo();
        List<Mensaje> emails = new ArrayList();
        for (Credencial c : credenciales) {
            String correo = c.getEmail();
            String pass = c.getPassword();
            String tipoCuenta = c.getTipoCuenta();

            if ("Gmail".equals(tipoCuenta)) {
                emails.addAll(cc.leerCorreoGmail(correo, pass));
            }
            if ("Hotmail-Outlook".equals(tipoCuenta)) {
                emails.addAll(cc.leerCorreoHotmail(correo, pass));
            }
        }
        emails.sort(Comparator.comparing(Mensaje::getFechaRecibido).reversed());

        String matriz[][] = new String[emails.size()][4];
        for (int i = 0; i < emails.size(); i++) {
            matriz[i][0] = emails.get(i).getAsunto();
            matriz[i][1] = emails.get(i).getFrom();
            matriz[i][2] = emails.get(i).getTo();
            matriz[i][3] = emails.get(i).getFechaRecibido();

        }
        mensajesTb.setModel(new DefaultTableModel(
                matriz, new String[]{
                    "Asunto", "Enviado por:", "Cuenta", "Fecha de Recibido"
                }
        ));

        mensajesTb.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ControladorMensaje cm = new ControladorMensaje();
                int seleccion = mensajesTb.rowAtPoint(evt.getPoint());
                String asunto = String.valueOf(mensajesTb.getValueAt(seleccion, 0));
                String de = String.valueOf(mensajesTb.getValueAt(seleccion, 1));
                String cuenta = String.valueOf(mensajesTb.getValueAt(seleccion, 2));
                String fecha = String.valueOf(mensajesTb.getValueAt(seleccion, 3));

                for (Mensaje mensaje : emails) {
                    String correo = mensaje.getTo();
                    String from = mensaje.getFrom();
                    String date = mensaje.getFechaRecibido();
                    String subject = mensaje.getAsunto();

                    if (cuenta.equals(correo) && de.equals(from) && fecha.equals(date) && asunto.equals(subject)) {
                        Part contenido = mensaje.getContenido();
                        cm.analizaParteDeMensaje(contenido);

                    }

                }

            }

        });
        
        activarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControladorSms sms=new ControladorSms();
                String telefono = celularTf.getText();
                for (Mensaje mensaje : emails) {
                    String asunto = filtroTf.getText();
                    String subject = mensaje.getAsunto();
                    String palabra[]=subject.split("\\s");
                    boolean respuesta;
                    
                    for(int i=0;i<palabra.length;i++)

                    if (asunto.equals(palabra[i])) {
                       respuesta=true;           
                    }
                    if(respuesta=true){
                        try {
                            sms.enviarSMS(telefono);
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        
                    }
                }
               
            }
        });
    }//GEN-LAST:event_inboxBtnActionPerformed

    private void alertaChbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertaChbActionPerformed
        // TODO add your handling code here:
        if (alertaChb.isSelected()) {
            activarBtn.setEnabled(true);
            celularTf.setEnabled(true);
            filtroTf.setEnabled(true);
        } else {
            activarBtn.setEnabled(false);
            celularTf.setEnabled(false);
            filtroTf.setEnabled(false);

        }
    }//GEN-LAST:event_alertaChbActionPerformed
//ScheduledExecutorService timer = Executors.newSingleThreadScheduledExecutor();
//timer.scheduleAtFixedRate(inboxBtnActionPerformed, 1, 1, TimeUnit.MINUTES);

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activarBtn;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JCheckBox alertaChb;
    private javax.swing.JTextField celularTf;
    private javax.swing.JTextField correoTf;
    private javax.swing.JTextField filtroTf;
    private javax.swing.JButton inboxBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable mensajesTb;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JPasswordField passTf;
    private javax.swing.JComboBox<String> tipoCuentaCb;
    // End of variables declaration//GEN-END:variables
}
